---
- hosts: all
  become: false
  tasks:
    # - name: Get ECR login password
    #   command: aws ecr get-login-password --region eu-central-1
    #   register: ecr_login

    - name: Pull image
      command: docker pull {{ lookup('env', 'REPOSITORY_URI') }}:latest
    - name: Run container
      ansible.builtin.command:
        cmd: docker run -d -p 8080:8080 {{ lookup('env', 'REPOSITORY_URI') }}:latest

