---
- hosts: all
  become: false
  tasks:
    - name: Get credentials
      command: aws ecr get-login-password --region {{ lookup('env', 'AWS_REGION') }}
      register: ecr_login

    - name: Login to ecr
      command:  docker login --username AWS --password-stdin {{ lookup('env', 'REPOSITORY_URI') }}
      args:
        stdin: "{{ ecr_login.stdout }}"

    - name: Pull image
      command: docker pull {{ lookup('env', 'REPOSITORY_URI') }}:latest

    - name: Run container
      ansible.builtin.command:
        cmd: docker run -d -p 8080:8080 {{ lookup('env', 'REPOSITORY_URI') }}:latest

